# Generated by Django 4.2.5 on 2023-10-05 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdetail',
            old_name='Product',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='cartdetail',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='Z1L044VC', max_length=20),
        ),
    ]
