# Generated by Django 4.2.5 on 2023-10-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_alter_cartdetail_quantity_alter_order_code'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartdetail',
            old_name='Product',
            new_name='product',
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='V0NLMI6M', max_length=20),
        ),
    ]
