# Generated by Django 4.2.5 on 2023-10-07 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_alter_order_code_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_After_coupon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='5AZ5XPY0', max_length=20),
        ),
    ]
