# Generated by Django 4.2.5 on 2023-10-07 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_cart_total_after_coupon_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='NSP55M4U', max_length=20),
        ),
    ]
